title: Snapshot HDR Imaging with a Polarization Camera
description: "A simple yet effective approach for turning a polarization camera into a snapshot HDR camera."
teaser: /assets/img/samples.webp
logo: /assets/img/lab-logo.png
authors: "Mingyang Xie*, Matthew Chan*, Christopher Metzler"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
github:
  is_project_page: false
  owner_url: https://github.com/intelligent-sensing
  owner_name: UMD Intelligent Sensing Lab
  # repository_url: https://github.com/intelligent-sensing/polarization-hdr
  repository_nwo: intelligent-sensing/polarization-hdr
# title: Snapshot High Dynamic Range Imaging with a Polarization Camera 
# logo: /assets/img/logo.png
# description: This paper presents a straightforward but highly effective approach for turning an off-the-shelf polarization camera into a high-performance HDR camera.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal
# github:
#   is_project_page: true
#   owner_url: https://www.github.com/intelligent-sensing
